//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by TestTraderApi.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDS_ABOUTBOX                    101
#define IDD_TRADER_MAIN_DLG             102
#define IDD_ABOUTBOX                    103
#define IDR_HTML_INSERTORDERDLG         104
#define IDR_MAINFRAME                   128
#define IDR_MAIN_MENU                   131
#define IDD_INSERT_ORDERS_DLG           132
#define IDD_CTP_USER                    133
#define IDI_STRATEGY_ICON24             145
#define IDI_STRATEGY_ICON               146
#define IDD_PARAMS_DLG                  147
#define IDD_ORDERS_DLG                  148
#define IDD_POSITIONS_DLG               149
#define IDD_STRATEGY_LOCAL_CL           150
#define IDD_TRADES_DLG                  151
#define IDD_INST_DLG                    152
#define IDD_RECOVER_DLG                 153
#define IDD_MD_DLG                      154
#define IDR_MD_MENU                     155
#define IDD_INST_MGR_DLG                156
#define IDD_DIALOG1                     157
#define IDD_INST_LIST_DLG               157
#define IDC_PUBLIC_MSG_LIST             1000
#define IDC_PRIVATE_MSG_LIST            1001
#define IDC_BUTTON2                     1005
#define IDC_BTNConnect                  1005
#define IDC_DELETE_INSTANCE_BTN         1005
#define IDC_CLEAR_INSTANCE_BTN          1005
#define IDC_REMOVEFROM_SUBLIST          1005
#define IDC_BUTTON3                     1006
#define IDC_START_STRATEGY_BTN          1006
#define IDC_ADD_BTN                     1006
#define IDC_BUTTON4                     1007
#define IDC_STOP_STRATEGY_BTN           1007
#define IDC_DELETE_BTN                  1007
#define IDC_BUTTON6                     1008
#define IDC_SCHEDULE_BTN                1008
#define IDC_DAY                         1010
#define IDC_MONEY                       1011
#define IDC_USER0                       1012
#define IDC_USERNAME                    1013
#define IDC_PRICE1                      1014
#define IDC_MONEY2                      1014
#define IDC_BALANCE                     1014
#define IDC_PRICE2                      1015
#define IDC_USER1                       1015
#define IDC_PRICEGAP                    1016
#define IDC_USERNAME2                   1016
#define IDC_USERNAME_CTP                1016
#define IDC_PRICETAG2                   1017
#define IDC_MONEY_CTP                   1017
#define IDC_PRICETAG1                   1018
#define IDC_BALANCE_CTP                 1018
#define IDC_STATUS1                     1019
#define IDC_STATUS2                     1020
#define IDC_STATIC_SELL1                1021
#define IDC_STATIC_BUY1                 1022
#define IDC_QRYORDERBTN                 1024
#define IDC_POSITIONS                   1025
#define IDC_QRYORDERS                   1029
#define IDC_QRYPOS_DETAILSBTN           1030
#define IDC_InstrumentID                1032
#define IDC_CloseOrOpen                 1033
#define IDC_OpenPrice                   1034
#define IDC_OpenVol                     1035
#define IDC_Direction                   1036
#define IDC_CHANGEMODE_BTN              1038
#define IDC_CHANGEMODE_BTN1             1038
#define IDC_MODE_STATIC                 1039
#define IDC_MODE_STATIC1                1039
#define IDC_CHANGEMODE_BTN2             1040
#define IDC_BUY_CHANGEMODE_BTN2         1040
#define IDC_BUY_MODE_STATIC2            1041
#define IDC_CLOSE_MODE2                 1042
#define IDC_SUM_PROFIT                  1043
#define IDC_BUY_CHANGEMODE_BTN1         1043
#define IDC_EXPORT_ORDERS_BTN           1044
#define IDC_CTP_USER_NAME               1045
#define IDC_CHANGE_CLOSEMODE2           1045
#define IDC_CTP_USER_PWD                1046
#define IDC_SELL_MODE_STATIC2           1046
#define IDC_CHANGEMODE_BTN3             1047
#define IDC_SELL_CHANGEMODE_BTN2        1047
#define IDC_CTP_USER_NAME_CTP           1047
#define IDC_STRA_RESET_BTN              1048
#define IDC_CTP_USER_PWD_CTP            1048
#define IDC_REFRESH_ORDER_COUNT_BTN     1049
#define IDC_CANCEL_ORDER_COUNT          1050
#define IDC_TRADED_ORDER_COUNT          1051
#define IDC_BUY_MODE_STATIC1            1052
#define IDC_OPEN_VOL                    1053
#define IDC_CLOSE_MODE1                 1053
#define IDC_OPEN_VOL_STATIC             1054
#define IDC_CONTRACT_NAME               1055
#define IDC_STRA1_STOPLESS1             1055
#define IDC_RESET_OPEN_VOL_BTN          1056
#define IDC_SUM_STATIC                  1057
#define IDC_STRA1_STOPLESS3             1058
#define IDC_PAR                         1058
#define IDC_PAR1                        1058
#define IDC_CHANGE_CLOSEMODE1           1059
#define IDC_SELL_MODE_STATIC1           1060
#define IDC_SELL_CHANGEMODE_BTN1        1061
#define IDC_RESET_RATIO_BTN             1070
#define IDC_WRITESTATIC_BTN             1071
#define IDC_WRITE_STATIC_BTN            1071
#define IDC_STRA1_STOPLESS2             1072
#define IDC_REFRESH_STOPLESS            1073
#define IDC_RESET_STOPLESS              1074
#define IDC_STRA2_STOPLESS              1075
#define IDC_STRA2_STOPLESS1             1075
#define IDC_STRA1_STOPLESS4             1076
#define IDC_PAR2                        1076
#define IDC_EDIT2                       1076
#define IDC_YDATE                       1076
#define IDC_STRATEGY_MAX_POSITION       1076
#define IDC_USER_PWD_CTP                1076
#define IDC_RESET_STOPLESS2             1077
#define IDC_PAR3                        1077
#define IDC_YYDATE                      1077
#define IDC_BUTTON5                     1078
#define IDC_DISPLAY_IN_MT4              1078
#define IDC_STRA2_STOPLESS3             1079
#define IDC_STRA2_STOPLESS2             1079
#define IDC_PAR4                        1080
#define IDC_REFRESH_DATA                1080
#define IDC_EQTIMETAG                   1083
#define IDC_COMBDirection               1085
#define IDC_COMBOPENCLOSE               1086
#define IDC_OPEN_PRICE                  1090
#define IDC_STRATEGY_TREE               1097
#define IDC_STRATEGY_NAME_STATIC        1098
#define IDC_MAINTAB                     1099
#define IDC_POSITIONS_LIST              1100
#define IDC_QRY_POSITIONS_BTN           1101
#define IDC_ORDERS_LIST                 1102
#define IDC_QRY_ORDERS_BTN              1103
#define IDC_PARAM_LIST                  1104
#define IDC_EDIT1                       1105
#define IDC_SAVE_BTN                    1106
#define IDC_INST_CODE                   1107
#define IDC_MAMUAL_ORDER_STRA           1108
#define IDC_STRATEGY_SHOWING            1109
#define IDC_DAY1                        1110
#define IDC_AVAIL_MON                   1111
#define IDC_AVAIL_MON2                  1112
#define IDC_STATUS_BOX                  1113
#define IDC_ADD_INSTANCE_BTN            1114
#define IDC_TOTAL_POSITION_D            1115
#define IDC_STRATEGY_POSITION_D         1116
#define IDC_MAX_POSITION                1117
#define IDC_SET_POSITION_LIMIT_BTN      1118
#define IDC_STRATEGY_LOCAL_CL_LIST      1119
#define IDC_QRY_STRA_LOCAL_CL_BTN       1120
#define IDC_TRADE_LST                   1121
#define IDC_STATIC_MD                   1122
#define IDC_MD_MSG_LIST                 1123
#define IDC_INST_LIST                   1125
#define IDC_COMB_InstCode               1126
#define IDC_STRATEGY_TOBE_RECOVER_LST   1127
#define IDC_RECOVER_PARAM_LIST          1128
#define IDC_RECOVER_ORDER_LIST          1129
#define IDC_RESTART_INSTANCE_BTN        1131
#define IDC_STATIC1                     1132
#define IDC_STATIC2                     1133
#define IDC_STATIC3                     1134
#define IDC_STATIC_BALANCE              1135
#define IDC_STATIC_BALANCE2             1136
#define IDC_CHECK1                      1136
#define IDC_CHECK_ESUN                  1136
#define IDC_CHECK_CTP                   1137
#define IDC_BUTTON1                     1137
#define IDC_SAVE_RECOV_ORDERS_BTN       1137
#define IDC_ADDINTO_SUBLIST             1137
#define IDC_SAVE_CL_BTN                 1137
#define IDC_MSG_LIST                    1139
#define IDC_USER_NAME_CTP               1140
#define IDC_CONNECT_MD_SERVER           1141
#define IDC_SUB_LIST                    1143
#define IDC_SUB_BTN                     1144
#define IDC_ALL_INST_LIST               1145
#define IDC_LIST1                       1146
#define IDC_MAX_CANCELTIME              1147
#define IDC_TOTAL_CANCELTIME_D          1148
#define IDC_STATIC_SEVERIP              1149
#define IDC_RS_SERVER_IP                1150
#define ID_INSERT_ORDER                 32772
#define ID_MENU_INSERT_ORDER            32773
#define ID_MENU_QRY_TRADEDORDER         32775
#define ID_MENU_QRY_TRADES              32776
#define ID_32777                        32777
#define ID_MENU_SETPARAS                32778
#define ID_MENU_OPTIONS                 32779
#define ID_32780                        32780
#define ID_MENU_PROFIT_ANALYZE          32781
#define ID_32782                        32782
#define ID_RECONNECT_TD                 32783
#define ID_32784                        32784
#define ID_MD_DLG                       32785
#define ID_32786                        32786
#define ID_32787                        32787
#define ID_MENU_INST_MGR                32788
#define ID_RECONNECT_MENU               32789
#define ID_32790                        32790
#define ID_ST_RECOVER                   32791

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        158
#define _APS_NEXT_COMMAND_VALUE         32792
#define _APS_NEXT_CONTROL_VALUE         1151
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
